version: '3.1'

services:
  mongo:
    image: mongo
    ports:
        - 27017:27017
    volumes:
        - data:/data/db
    networks:
        - microservicenetwork
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: ENTERPASSWORD

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    networks:
    - microservicenetwork
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: ENTERPASSWORD

networks:
    microservicenetwork:
        external: true

volumes:
    data:
        driver: local