version: '3.3'

services:
  registry:
    image: "registry:2"
    ports:
      - 5000:5000
    labels:
      NAME: "registry"
    volumes:
      - data:/var/lib/registry

volumes:
  data:
      driver: local